### ISSUE TITLE
报错 不知道是不是我自己原因

### ISSUE THREAD

**Issue by knowledgeablelmh** [qitoqito/kedaya#9]
🐯 导入跳过: jd_extra_wuxian.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_help_sendBean.js 已经添加过了
🐯 导入跳过: jd_help_videoBean.js 如需运行请手动添加定时
🐯 导入跳过: jd_help_yuanxiao.js 如需运行请手动添加定时
🐯 导入跳过: jd_reward_menghu.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_addCart.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_assets.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_beanLottery.js 已经添加过了
🐯 导入跳过: jd_task_carnivalCity.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_carplay.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_checkCookie.js 已经添加过了
🐯 导入跳过: jd_task_chinaJoy.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_chunwan.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_comment.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_farm.js 已经添加过了
🐯 导入跳过: jd_task_goldCenter.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_guangPlus.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_hby.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_hudong.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_ifanli.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_invokeKey.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_jd2xd.js 已经添加过了
🐯 导入跳过: jd_task_jdjoy.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_jimofang.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_lottery.js 已经添加过了
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_manghe.js 已经添加过了
🐯 导入跳过: jd_task_morningBean.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_nianhuo.js 如需运行请手动添加定时
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'includes')
    at /ql/scripts/qitoCreat.js:200:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
🐶 导入失败: jd_task_pet.js 已经添加过了

**Comment by qitoqito** [comment]
删除scripts/parse目录 重新拉库 可能你目录放了其他文件引入错误

**Comment by knowledgeablelmh** [comment]
🐶 导入失败: jd_task_jd2xd.js 已经添加过了
🐯 导入跳过: jd_task_jdjoy.js 如需运行请手动添加定时
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
🐼 禁用成功: jd_task_jimofang.js 已经成功禁用
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
🐶 导入失败: jd_task_lottery.js 已经添加过了
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
Cannot read properties of undefined (reading 'includes')
🐶 导入失败: jd_task_manghe.js 已经添加过了
🐯 导入跳过: jd_task_morningBean.js 如需运行请手动添加定时
🐯 导入跳过: jd_task_nianhuo.js 如需运行请手动添加定时

**Comment by knowledgeablelmh** [comment]
@qitoqito   你好，还是报错了

**Comment by qitoqito** [comment]
不清楚,而且你这个报错很奇怪,定时任务里面没有任务或者没有任务名引起的报错
`if (z.name.includes(label) && z.command.includes(`task ${filename}`)) {`

自己检查下其他定时

**Comment by knowledgeablelmh** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/83534987/162451214-1bc0781a-ee01-4cff-ab12-90bd7f0c445d.png">
添加了任务名

**Comment by knowledgeablelmh** [comment]
@qitoqito 找到问题了，原来是因为其他任务没有名称引起的。。。
